"""added area_id to DevelopmentPlan

Revision ID: b1c7b9823e2c
Revises: 
Create Date: 2025-10-22 00:25:46.219514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c7b9823e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('polygon_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_developmentplan_polygon_id', 'polygons', ['polygon_id'], ['id']
)

    with op.batch_alter_table('development_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.alter_column('polygon_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_developmentplan_area_id', 'areas', ['area_id'], ['id'])
        batch_op.create_foreign_key('fk_developmentplan_polygon_id', 'polygons', ['polygon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_developmentplan_area_id', type_='foreignkey')
        batch_op.drop_constraint('fk_developmentplan_area_id', type_='foreignkey')
        batch_op.alter_column('polygon_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('area_id')

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_developmentplan_area_id', type_='foreignkey')
        batch_op.alter_column('polygon_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
